name: Helm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Helm tool installer
      uses: Azure/setup-helm@v1
      with:
        version: v3.3.0

    - name: Check out code
      uses: actions/checkout@v2 
      with:
        fetch-depth: 0  

    - name: Check changes
      id: check-changes
      uses: rdietrick/did-files-change@v1.2
      with:
        pathspec: charts

    - name: helm lint
      if: ${{ steps.check-changes.outputs.changed }}
      run: helm lint charts/ngingo


