name: Helm

on:
  push:
    branches: [ master ]
    paths:
      - 'charts/*'
  pull_request:
    branches: [ master ]
    paths:
      - 'charts/**'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Helm tool installer
      uses: Azure/setup-helm@v1
      with:
        version: v3.3.0

    - name: Check out code
      uses: actions/checkout@v2 

    - name: helm lint
      if: ${{ steps.check-changes.outputs.changed }}
      run: helm lint charts/ngingo


