name: label

on:
  pull_request:
    types: [ opened, edited, reopened]

jobs:

  triage:
    name: triage
    runs-on: ubuntu-latest
    steps: 

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - uses: actions/labeler@main
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler-config.yml   