name: release

on:
  push:
    tags:        
      - 'v*' 

jobs:
  dockerBuild:
    name: dockerBuild
    runs-on: ubuntu-latest
    steps: 

    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.prod
        platforms: linux/amd64,linux/arm64,linux/386
        push: true
        tags: samincl/ngingo:${{steps.tag.outputs.tag}}  

  release:
    name: release
    runs-on: ubuntu-latest
    needs: dockerBuild
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false